### ISSUE TITLE
Pokies lab

### ISSUE THREAD

**Issue by HarshaRaptor** [win11react/store#10]
### App Type

Game

### App URL

https://pokieslab.com/free-online-pokies/

### App Icon

https://pokieslab.com/wp-content/uploads/pokieslab-white.svg

### App Description

contains a lot of games within(classic games)

**Comment by blueedgetechno** [comment]
NOOOO, no gampling games

**Comment by Lukas-Batema** [comment]
Lot's of classic games, like closing the issue?
