### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by soarnote** [win11react/store#22]
### >>App or Game Name>>

1v1.lol

### >>App Type>>

Game

### >>App URL>>

HTTP/2 200 cache-control: no-cache content-type: text/html; charset=utf-8 etag: "e639ad7976a7b684d618b52659402b24b05f74a1510835bcfddc8e1bcf8d6b52" last-modified: Mon, 14 Feb 2022 10:27:02 GMT strict-transport-security: max-age=31556926 accept-ranges: bytes date: Wed, 16 Feb 2022 19:39:53 GMT x-served-by: cache-fra19138-FRA x-cache: MISS x-cache-hits: 0 x-timer: S1645040393.471101,VS0,VE217 vary: x-fh-requested-host, accept-encoding

### >>App Description>>

its like fornite

**Comment by Lukas-Batema** [comment]
No, no fortnite-like games!
