### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by MelonicOverlord** [win11react/store#50]
### Name

Super Smash Aeugh Web

### Type

game

### URL

https://melonicoverlord.github.io/aeughweb/

### Icon

yeah but i cannot get the link so um it's in the super mods channel (the pufferfish)

### Description

Work In Progress, hopefully will maybe exist soon idk?

https://github.com/MelonicOverlord/aeughweb/ -- github repo

**Comment by MelonicOverlord** [comment]
Original Repos:

https://github.com/MFHKiwi/super-smash-aeugh
https://github.com/MelonicOverlord/super-smash-aeugh

**Comment by andrewstech** [comment]
Remade https://github.com/win11react/store/issues/53
