### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by Pixel556** [win11react/store#80]
### Name

Google

### Type

app

### URL

https://google.com

### Icon

https://cdn.icon-icons.com/icons2/1269/PNG/512/1497553309-101_84843.png

### Description

Google is an easy way to search for what you want. We also include more services like YouTube, Forms, Gmail and more!

**Comment by MalikIdreesHasanKhan** [comment]
Not iframeable. Please close this issue.

**Comment by Pixel556** [comment]
Ok
