### ISSUE TITLE
Add Minecraft Java pls

### ISSUE THREAD

**Issue by xboxplayer0161** [win11react/store#82]
### Name

Minecraft Java

### Type

game

### URL

https://g.eags.us/eaglercraft/game.html

### Icon

https://th.bing.com/th/id/R.ea7d596deda6d0ba9e912ea5e1add0e4?rik=D9v30aWNg%2bR5Jw&pid=ImgRaw&r=0

### Description

Minecraft.... A Blocky World in the Cosmo's. The Only Squared- Dream: LETS SPEEDRUN LADS...Narrator: IT ONLY HAVE MULTIPLAYER!

**Comment by Lukas-Batema** [comment]
We cannot iFrame a non-web game/application xD
