### ISSUE TITLE
Antistress game

### ISSUE THREAD

**Issue by MehRadson** [win11react/store#87]
### Name

Antistress

### Type

game

### URL

https://gameforge.com/en-US/littlegames/anti-stress-game/#

### Icon

https://www.jindoblu.com/wp-content/uploads/12_Antistress_Icona-1.png

### Description

This is Antistress. It's an online game to relax your mind! Enjoy!!

**Comment by Lukas-Batema** [comment]
New account go brr, this game didn't help me relax because it is probably a virus!
