### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by Nepalix** [win11react/store#88]
### Name

Henry Stickmin Colllection

### Type

game

### URL

https://store.steampowered.com/app/1089980/The_Henry_Stickmin_Collection/

### Icon

https://ru.wikipedia.org/wiki/Файл:PuffballsUnitedTheHenryStickminCollection.png

### Description

The Henry Stickmin Collection is a Newgrounds choose-your-own-path classic, reborn and revitalized. This 6-game epic culminates in multiple entire canon, extremely different endings. Each step of the journey has you choose from options such as a Teleporter or calling in your buddy Charles to help you out.

**Comment by yashash1511** [comment]
not possible as not a web app also it is paid
